### ISSUE TITLE
Tensor Tensor("dense_2/Sigmoid:0", shape=(?, 1), dtype=float32) is not an element of this graph.

### ISSUE THREAD

**Issue by johnneed** [TheTimKiely/SafeToSwim#8]
Traceback (most recent call last)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_val

**Comment by johnneed** [comment]
I'm running this in Docker and getting this after I upload an image.

**Comment by TheTimKiely** [comment]
Awesome!  It works fine on Windows, but I'm getting this same error on Linux.
I'll start digging...

**Comment by rubanraj-r** [comment]
I am running inside a flask server. I get this error in the model.predict() line. I am taking the image from local directory.
